version: "3.9"
services:

    az:
      image: mcr.microsoft.com/azure-cli:2.9.1
      env_file: .env
      entrypoint: /usr/local/bin/az
      volumes:
        - .:/workspace
        - .azure:/root/.azure
      working_dir: /workspace

    jq:
      image: imega/jq:1.6

    terraform:
      image: hashicorp/terraform:0.14.7
      env_file: .env
      volumes:
        - .:/workspace
      working_dir: /workspace